name: 'php-nginx-cloudflarfed-tunnel'
runs:
  using: "composite"
  steps:
    - run: docker run -p 9000:9000 -d php:7.4.29-fpm
      shell: bash
    - run: |
        ls
        pwd
      shell: bash
    - run: docker run -p 80:80 -v $(pwd)/default.conf:/etc/nginx/conf.d/default.conf -v $(pwd)/src:/usr/share/nginx/html -d nginx
      shell: bash
    - run: curl 127.0.0.1:80
      shell: bash
